/* Generated By:JavaCC: Do not edit this line. ATSNwaParserConstants.java */
package util.parser.nwa.ats;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATSNwaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFTPARA = 7;
  /** RegularExpression Id. */
  int RIGHTPARA = 8;
  /** RegularExpression Id. */
  int LEFTCURLY = 9;
  /** RegularExpression Id. */
  int RIGHTCURLY = 10;
  /** RegularExpression Id. */
  int AUTOMATON = 11;
  /** RegularExpression Id. */
  int ALPHABET_INTERNAL = 12;
  /** RegularExpression Id. */
  int ALPHABET_CALL = 13;
  /** RegularExpression Id. */
  int ALPHABET_RETURN = 14;
  /** RegularExpression Id. */
  int ASSIGNMENT = 15;
  /** RegularExpression Id. */
  int STATES = 16;
  /** RegularExpression Id. */
  int INITSTATES = 17;
  /** RegularExpression Id. */
  int FINALSTATES = 18;
  /** RegularExpression Id. */
  int TRANSITIONS_INTERNAL = 19;
  /** RegularExpression Id. */
  int TRANSITIONS_CALL = 20;
  /** RegularExpression Id. */
  int TRANSITIONS_RETURN = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int STRING = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"NestedWordAutomaton\"",
    "\"internalAlphabet\"",
    "\"callAlphabet\"",
    "\"returnAlphabet\"",
    "\"=\"",
    "\"states\"",
    "\"initialStates\"",
    "\"finalStates\"",
    "\"internalTransitions\"",
    "\"callTransitions\"",
    "\"returnTransitions\"",
    "\",\"",
    "\";\"",
    "<STRING>",
  };

}
