/* Generated By:JavaCC: Do not edit this line. ATSParserConstants.java */
package util.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ATSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFTPARA = 7;
  /** RegularExpression Id. */
  int RIGHTPARA = 8;
  /** RegularExpression Id. */
  int LEFTCURLY = 9;
  /** RegularExpression Id. */
  int RIGHTCURLY = 10;
  /** RegularExpression Id. */
  int AUTOMATON = 11;
  /** RegularExpression Id. */
  int ALPHABET = 12;
  /** RegularExpression Id. */
  int ASSIGNMENT = 13;
  /** RegularExpression Id. */
  int STATES = 14;
  /** RegularExpression Id. */
  int INITSTATES = 15;
  /** RegularExpression Id. */
  int FINALSTATES = 16;
  /** RegularExpression Id. */
  int TRANSITIONS = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int STRING = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"FiniteAutomaton\"",
    "\"alphabet\"",
    "\"=\"",
    "\"states\"",
    "\"initialStates\"",
    "\"finalStates\"",
    "\"transitions\"",
    "\",\"",
    "\";\"",
    "<STRING>",
  };

}
